name: Context testing

on:
    push:

jobs:
    dump_context_to_logs:
        runs-on: ubuntu-latest
        steps:
          - name: Dump Github Context
            env:
              GITHUB_CONTEXT: ${{ toJson(github) }}
            run: echo "$GITHUB_CONTEXT"

          - name: Dump Job Context
            env:
                JOB_CONTEXT: ${{ toJson(job) }}
            run: echo "$JOB_CONETXT"

          - name: Dump step conetxt
            env:
                STEPS_CONTEXT: ${{ toJson(steps) }}
            run: echo "$STEPS_CONTEXT"

          - name: dump runner context
            env:
                : ${{ toJson(runner) }}
            run: echo "$RUNNER_CONTEXT"

          - name: dump secret context
            env:
                SECRET_CONTEXT: ${{ toJson(secrets) }}
            run: echo "$SECRET_CONTEXT"