name: Generate ASCII ARtwork

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
        # - name: checkout repo
        #   uses: actions/checkout@v5

        - name: Install Cowsay program
          run: sudo apt-get install cowsay -y
            
        - name: Execute cowsay command
          run: cowsay -f dragon "Run for cover, I am a Dragon....RAWR" >> dragon.txt

        # - name: Sleep for 30 seconds
        #   run: sleep 30

        - name: Upload the dragon text file
          uses: actions/upload-artifact@v4
          with:
            name: dragon-text-file
            path: dragon.txt

    test_job:
      needs: build_job
      runs-on: ubuntu-latest
      steps:

      - name: Download the dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file

    #   - name: Sleep for 30 seconds
    #     run: sleep 30

      - name: test file exists
        run: grep -i "dragon" dragon.txt

        # - name: Read file
        #   run: cat dragon.txt

    deploy_job:
      needs: test_job
      runs-on: ubuntu-latest
      steps:
      - name: Download the dragon text file
        uses: actions/download-artifact@v4
        with:
          name: dragon-text-file
          
      - name: Read file
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying......"

        # - name: Executing shell script
        #   run: |
        #     chmod +x ascii-script.sh
        #     ./ascii-script.sh